### PR TITLE
Update appdynamics.github.io to ciscodevnet.github.io

### PR DESCRIPTION
**Pull request by subhashiyer07**

### CODE REVIEW

**Comment by subhashiyer07** [comment]
@avinashk442 I have updated all references in this repo. 
Can you point to any other repo that needs to be changed?
cluster agent and machine agent readme has been changed here

**Review by bhumijgupta — APPROVED** [review]
This seems to be working fine. Just a minor nit-picks:
We should also update the icon field to `https://raw.githubusercontent.com/Appdynamics/appdynamics-charts/master/logo.png` in `index.yaml`

cc @akshitgrover

**Comment by subhashiyer07** [comment]
> This seems to be working fine. Just a minor nit-picks:
> We should also update the icon field to `https://raw.githubusercontent.com/CiscoDevNet/appdynamics-charts/master/logo.png` in `index.yaml`
> 
> cc @akshitgrover

@bhumijgupta 
Updated the references to logo and dockerfile. Please check

**Comment by bhumijgupta** [comment]
@subhashiyer07 LGTM 🚀

**Comment by akshitgrover** [comment]
Fixes #20

**Pull request merged**
